# settings.py

TOKEN_TELEGRAM = "COLE_SEU_TOKEN_DO_BOT_AQUI"
ID_CHAT_TELEGRAM = "COLE_SEU_ID_AQUI"

BANCA_INICIAL = 200  # em reais
RISCO_POR_OPERACAO = 0.02  # 2%
ATIVO_ANALISADO = "WINM25"  # mini índice atual
